# Generated by Django 4.2.29 on 2026-04-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_card_photo',
            new_name='id_card_recto',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_card_verso',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
