# Generated by Django 4.2.29 on 2026-03-31 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('molecule', models.CharField(blank=True, help_text='Principe actif', max_length=200)),
                ('category', models.CharField(choices=[('cardio', 'Cardiologie'), ('diabetes', 'Diabétologie'), ('antibiotic', 'Antibiotique'), ('analgesic', 'Analgésique'), ('anti_inflam', 'Anti-inflammatoire'), ('gastro', 'Gastro-entérologie'), ('neuro', 'Neurologie'), ('other', 'Autre')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('form', models.CharField(blank=True, help_text='Ex: Sirop, Comprimé, Pommade', max_length=50)),
                ('dosage_forms', models.JSONField(default=list, help_text='Ex: ["500mg", "1g"]')),
                ('side_effects', models.TextField(blank=True)),
                ('interactions', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('price_dzd', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de référence', max_digits=10, null=True)),
                ('cnas_covered', models.BooleanField(default=False)),
                ('is_shifa_compatible', models.BooleanField(default=False)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Médicament (Référence)',
                'verbose_name_plural': 'Médicaments (Références)',
                'ordering': ['name'],
            },
        ),
    ]
