# Generated by Django 4.2.29 on 2026-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='form',
            field=models.CharField(blank=True, help_text='Ex: Sirop, Comprimé, Pommade', max_length=250),
        ),
        migrations.AlterField(
            model_name='medication',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='medication',
            name='molecule',
            field=models.CharField(blank=True, help_text='Principe actif', max_length=250),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
