# Generated by Django 4.2.29 on 2026-03-31 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0002_delete_medication'),
        ('medications', '0001_initial'),
        ('pharmacy', '0003_pharmacyorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacyorder',
            options={},
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='caretaker',
            field=models.ForeignKey(blank=True, help_text='Garde-malade assigné si applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='order_type',
            field=models.CharField(choices=[('prescription', "Préparation d'ordonnance"), ('direct', 'Achat direct')], default='prescription', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacyorder',
            name='withdrawal_method',
            field=models.CharField(choices=[('patient', 'Retrait par le patient'), ('caretaker', 'Retrait par le garde-malade')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='prescriptions.prescription'),
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Prix de vente DZD en pharmacie', max_digits=8)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_stocks', to='medications.medication')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacy.pharmacist')),
            ],
            options={
                'unique_together': {('pharmacist', 'medication')},
            },
        ),
    ]
