# Generated by Django 4.2.29 on 2026-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_pharmacyorder_options_pharmacist_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix total de la commande', max_digits=10),
        ),
    ]
