# Generated by Django 4.2.29 on 2026-04-05 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_pharmacyorder_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacy_license',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy_licenses/'),
        ),
        migrations.CreateModel(
            name='PharmacistQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('graduation_year', models.PositiveIntegerField()),
                ('degree_type', models.CharField(max_length=100)),
                ('scan', models.FileField(upload_to='pharmacist_qualifications/')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='pharmacy.pharmacist')),
            ],
        ),
    ]
