# Generated by Django 4.2.29 on 2026-04-05 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0003_caretaker_is_available_carerequest_caremessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('date_obtained', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('scan', models.FileField(upload_to='caretaker_certificates/')),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='caretaker.caretaker')),
            ],
        ),
    ]
