# Generated by Django 4.2.29 on 2026-04-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaker', '0004_caretakercertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='professional_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
