# Generated by Django 4.2.29 on 2026-03-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
