# Generated by Django 4.2.29 on 2026-03-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('prescriptions', '0002_delete_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='medications.medication'),
        ),
    ]
