# Generated by Django 4.2.29 on 2026-03-31 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_weeklyschedule_dayoff'),
        ('appointments', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='motif',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='refusal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'date', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='slot',
        ),
        migrations.DeleteModel(
            name='AvailabilitySlot',
        ),
    ]
