# Generated by Django 4.2.29 on 2026-04-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_practice_authorization_doctorqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_professionel_info',
            name='diploma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_infos', to='doctors.doctorqualification'),
        ),
    ]
